#!/usr/bin/env bash

## plugin purpose: list containers and images for a certain pod
# plugin usage: kubectl podinspect <namespace>

# Check if namespace is provided as argument
if [ -z "$1" ]
then
    echo "Usage: kubectl po <namespace>"
    echo "Current namespaces are:"
    kubectl get ns
    exit 1
else
    # list pods in namespace
    kubectl get pods -n $1
fi

# Get pod name
echo "Enter pod name:"
read pod_name

# Get containers running in the pod
containers=$(kubectl get pod $pod_name -n $1 -o jsonpath="{.spec.containers[*].name}")
images=$(kubectl get pod $pod_name -n $1 -o jsonpath="{.spec.containers[*].image}")

# write container with images to stdout
echo -e "🔎 Containers running in the pod: ${containers} \n"
echo -e "🔎 Images used by the containers: ${images} \n"