# Use the Alpine Linux base image
FROM alpine:latest

# Update the package repository and install OpenSSL
RUN apk update && \
    apk upgrade && \
    apk add --no-cache openssl && \
    apk add --no-cache curl

# for older alpine versions
# rm -rf /var/cache/apk/*

WORKDIR /app

COPY postgresql_reporter.sh /app/postgresql_reporter.sh
# Set the default command to run when the container starts
CMD ["/bin/sh"]