apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-11-13T14:08:07Z"
  generation: 2
  labels:
    app: webapp
  name: webapp
  namespace: default
  resourceVersion: "970199"
  uid: 0f8c4463-7d7c-4712-9c0c-1f7d3686a29c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
    spec:
      containers:
      - image: dejanualex/go_hello:1.0
        imagePullPolicy: IfNotPresent
        name: go-hello-9w7fk
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-11-13T14:08:09Z"
    lastUpdateTime: "2023-11-13T14:08:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-13T14:08:07Z"
    lastUpdateTime: "2023-11-13T14:08:09Z"
    message: ReplicaSet "webapp-7ffcf85fdd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
